### PR TITLE
Updates for Dropwizard 4.0.x

### PR DESCRIPTION
**Pull request by michaeljohnalbers**
Updates for Dropwizard 4.0.

For #4.

### CODE REVIEW

**Comment by mtakaki** [comment]
Thanks again for another PR. Lemme just fix the build for master and then I'll get yours merged.

**Comment by michaeljohnalbers** [comment]
@mtakaki Any ETA when this might get merged and released?

**Comment by dcojo** [comment]
Hi,
Are there any updates on this ?  Thank you !

**Comment by mtakaki** [comment]
Sorry about the delay! Thank you so much again for creating this PR!

**Pull request merged**
